channels:
  - conda-forge
  - bioconda
dependencies:
  - wget
  - unzip
  - git
  - python=2.7
  - pip
  - r-base
  - fastqc=0.10.1 # +dfsg-2
  - cutadapt=1.2.1
  - bwa=0.7.12
  - samtools=0.1.19-1
  - bedtools=2.17.0-1
  # - grohmm
  - sratoolkit=2.5.4
